export const ORDER_TAG = "order"
export const USER_INFO = "userInfo"

export const PROVIDER_KEY = "provider"
export const EMPLOYEE_KEY = "employee"
export const CLIENT_KEY = "client"
export const OPEN_DESK_KEY = "open_desk"
export const ADD_ITEMS_TO_ORDER_KEY = "add_items_to_order"
export const DELETE_ORDER_KEY = "delete_order"

export const CASH_ROLE = "caixa"
export const CLIENT_ROLE = "cliente"

export const STATUS_STARTING = "enviado"
export const STATUS_PREPARING = "preparando"
export const STATUS_PREPARED = "preparado"

export const INICIO_ROUTE = "/menu/inicio"
export const KITCHEN_ROUTE = "/menu/cozinha"
export const DESKS_ROUTE = "/menu/mesas"
export const DASHBOARD_ROUTE = "/menu/dashboard"
export const DASHBOARD_DETAIL_ROUTE = "/menu/dashboard/detail"
export const CASHIER_ROUTE = "/menu/caixa"
export const CLIENTS_ROUTE = "/menu/clientes"
export const MENU_ROUTE = "/menu/cardapio"