export const BUSINESS_COLLECTION = "business"
export const USERS_COLLECTION = "users"
export const DESKS_COLLECTION = "desks"
export const ORDERS_COLLECTION = "orders"
export const ORDERED_ITEMS_COLLECTION = "orderedItems"
export const MENU_ITEMS_COLLECTION = "menuItems"
export const GAINS_COLLECTION = "gains"
export const EXPENSES_COLLECTION = "expenses"